In [1]:
import pandas as pd
from pathlib import Path

In [2]:
spotify_df=pd.read_csv(Path('../Resources/spotify_data.csv'))

C:\Users\Owner\AppData\Local\Temp\ipykernel_26072\953258888.py:1: DtypeWarning: Columns (7,8,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(Path('../Resources/spotify_data.csv'))

In [3]:
spotify_df.head()

,Country,Uri,Popularity,Title,Artist,Album/Single,Genre,Artist_followers,Explicit,Album,...,Spain,Sweden,Switzerland,Turkey,UK,USA,Popu_max,Top10_dummy,Top50_dummy,Cluster
0,Global,https://open.spotify.com/track/6FyRXC8tJUh863J...,31833.95,adan y eva,Paulo Londra,single,argentine hip hop,11427104,False,Adan y Eva,...,0,0,0,0,0,0,10,1,1,global
1,USA,https://open.spotify.com/track/6FyRXC8tJUh863J...,8.00,adan y eva,Paulo Londra,single,argentine hip hop,11427104,False,Adan y Eva,...,0,0,0,0,0,1,191,0,0,english speaking and nordic
2,Argentina,https://open.spotify.com/track/6FyRXC8tJUh863J...,76924.40,adan y eva,Paulo Londra,single,argentine hip hop,11427104,False,Adan y Eva,...,0,0,0,0,0,0,1,1,1,spanish speaking
3,Belgium,https://open.spotify.com/track/6FyRXC8tJUh863J...,849.60,adan y eva,Paulo Londra,single,argentine hip hop,11427104,False,Adan y Eva,...,0,0,0,0,0,0,126,0,0,english speaking and nordic
4,Switzerland,https://open.spotify.com/track/6FyRXC8tJUh863J...,20739.10,adan y eva,Paulo Londra,single,argentine hip hop,11427104,False,Adan y Eva,...,0,0,1,0,0,0,21,0,1,english speaking and nordic

In [4]:
spotify_df.isnull().sum()

Country        0
Uri            0
Popularity     0
Title          0
Artist         0
              ..
USA            0
Popu_max       0
Top10_dummy    0
Top50_dummy    0
Cluster        0
Length: 150, dtype: int64

In [5]:
spotify_df.describe

<bound method NDFrame.describe of             Country                                                Uri  \
0            Global  https://open.spotify.com/track/6FyRXC8tJUh863J...
1               USA  https://open.spotify.com/track/6FyRXC8tJUh863J...
2         Argentina  https://open.spotify.com/track/6FyRXC8tJUh863J...
3           Belgium  https://open.spotify.com/track/6FyRXC8tJUh863J...
4       Switzerland  https://open.spotify.com/track/6FyRXC8tJUh863J...
...             ...                                                ...
166851       Turkey  https://open.spotify.com/track/6IYfi7SufZ6k02U...
166852       Turkey  https://open.spotify.com/track/5evWFJpbKC8QN6P...
166853       Turkey  https://open.spotify.com/track/6KJaFzgieN31wbM...
166854       Turkey  https://open.spotify.com/track/03Qa4yCUzzXK5Rt...
166855       Turkey  https://open.spotify.com/track/6eJQWdK5fRPzc0S...

        Popularity               Title                           Artist  \
0         31833.95          adan y eva                     Paulo Londra
1             8.00          adan y eva                     Paulo Londra
2         76924.40          adan y eva                     Paulo Londra
3           849.60          adan y eva                     Paulo Londra
4         20739.10          adan y eva                     Paulo Londra
...            ...                 ...                              ...
166851       45.60             shadows  Tinie Tempah - Bipolar Sunshine
166852      247.40             tarumar                              Åžam
166853      365.85     Ã§irkin Ã¶rdekler                        Cash Flow
166854      589.60  bir elmanÄ±n yarÄ±sÄ±                     Mehmet Erdem
166855        2.40                 nwa                           Motive

       Album/Single              Genre Artist_followers Explicit  \
0            single  argentine hip hop         11427104    False
1            single  argentine hip hop         11427104    False
2            single  argentine hip hop         11427104    False
3            single  argentine hip hop         11427104    False
4            single  argentine hip hop         11427104    False
...             ...                ...              ...      ...
166851        album          dance pop         734985.0     True
166852       single    turkish hip hop         108479.0    False
166853        album    turkish hip hop         124767.0    False
166854        album       turkish jazz         481608.0    False
166855        album    turkish hip hop          57470.0    False

                        Album  ... Spain Sweden Switzerland Turkey UK USA  \
0                  Adan y Eva  ...     0      0           0      0  0   0
1                  Adan y Eva  ...     0      0           0      0  0   1
2                  Adan y Eva  ...     0      0           0      0  0   0
3                  Adan y Eva  ...     0      0           0      0  0   0
4                  Adan y Eva  ...     0      0           1      0  0   0
...                       ...  ...   ...    ...         ...    ... ..  ..
166851                  YOUTH  ...     0      0           0      1  0   0
166852                  Vehim  ...     0      0           0      1  0   0
166853   SuÃ§ SokaÄŸÄ± Sakinleri  ...     0      0           0      1  0   0
166854   Hepsi Benim YÃ¼zÃ¼mden  ...     0      0           0      1  0   0
166855  M.O.B Mixtape, Vol. 1  ...     0      0           0      1  0   0

       Popu_max Top10_dummy Top50_dummy  \
0            10           1           1
1           191           0           0
2             1           1           1
3           126           0           0
4            21           0           1
...         ...         ...         ...
166851      144           0           0
166852       36           0           1
166853       74           0           0
166854      156           0           0
166855      198           0           0

                                        Cluster
0                                        global
1                   english speaking and nordic
2                              spanish speaking
3                   english speaking and nordic
4                   english speaking and nordic
...                                         ...
166851  southern europe and portuguese heritage
166852  southern europe and portuguese heritage
166853  southern europe and portuguese heritage
166854  southern europe and portuguese heritage
166855  southern europe and portuguese heritage

[166856 rows x 150 columns]>

In [6]:
spotify_df.describe()

,Popularity,Days_since_release,Released_after_2017,Explicit_false,Explicit_true,album,compilation,single,bolero,boy band,...,Singapore,Spain,Sweden,Switzerland,Turkey,UK,USA,Popu_max,Top10_dummy,Top50_dummy
count,166856.000000,163728.000000,163728.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,...,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000,166856.000000
mean,5501.319946,1332.208052,0.848199,0.644166,0.355804,0.550571,0.014941,0.434458,0.001271,0.011819,...,0.021713,0.025699,0.041773,0.046064,0.020167,0.039195,0.039825,89.397828,0.088603,0.298773
std,13204.173859,2468.608825,0.358829,0.478767,0.478758,0.497438,0.121317,0.495687,0.035622,0.108069,...,0.145746,0.158236,0.200070,0.209624,0.140572,0.194060,0.195548,58.028813,0.284171,0.457721
min,0.800000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,79.200000,423.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.000000,0.000000,0.000000
50%,534.875000,827.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,84.000000,0.000000,0.000000
75%,4001.350000,1233.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,138.000000,0.000000,1.000000
max,233766.900000,44128.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,200.000000,1.000000,1.000000